//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.Guests = new HashSet<Guest>();
            this.MeetingEmployees = new HashSet<MeetingEmployee>();
            this.Notes = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public Nullable<System.DateTime> Meeting_Date { get; set; }
        public Nullable<System.DateTime> Date_Scheduled { get; set; }
        public string Topic { get; set; }
        public Nullable<int> MeetingStatus_id { get; set; }
        public Nullable<int> MeetingType_id { get; set; }
        public Nullable<System.DateTime> Pause_Start_Time { get; set; }
        public Nullable<System.DateTime> Pause_End_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingEmployee> MeetingEmployees { get; set; }
        public virtual MeetingStatu MeetingStatu { get; set; }
        public virtual MeetingType MeetingType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
    }
}
