//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Note_Date { get; set; }
        public Nullable<System.DateTime> Note_Time { get; set; }
        public string NoteType { get; set; }
        public Nullable<int> Meeting_id { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
